config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'

  resources :users
  resources :super_users
  resources :posts
  resources :sessions
  get "logout", to: "sessions#destroy", as: "logout"
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord 
    belongs_to :user
    
    validates :title, :content, presence: true

end 

app/models/user.rb
class User < ApplicationRecord 
    has_secure_password
    has_many :posts

    validates :email, :user_name, presence: true, uniqueness: true
    validates :first_name, :last_name, presence: true

    
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user 
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        end
    end 

    def redirect_unless_admin 
        redirect_to posts_path unless current_user && current_user.admin 
    end 

    def logged_in?
        !!session[:user_id]
    end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index

    end 
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[ show edit update destroy ]
    before_action :redirect_unless_admin, only: %i[ new edit update destroy ]
  
      def index
        @posts = Post.all
      end 
  
      def new
        @post = Post.new
      end
  
      def show 
        @post = Post.find(params[:id])
      end 
  
      def edit 
      end
  
      def create
        @post = current_user.posts.build(post_params)
          if @post.save
            redirect_to @post, notice: "Post was successfully created." 
          else
            render :new
          end
        end
  
        def update
          if @post.update(post_params)
            redirect_to @post, notice: "Post was successfully updated." 
          else
            render :edit
          end
        end
  
        def destroy
          @post.destroy
          redirect_to posts_url, notice: "Post was successfully destroyed." 
        end
  
  
        private
        def set_post
          @post = Post.find(params[:id])
        end
    
        def post_params
          params.require(:post).permit(:title, :content, :image_link, :premium, :user_id)
        end
  
  end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
          if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user, notice: "User was successfully created." 
          else
            render :new
          end
      end

      def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Session was successfully destroyed." 
      end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]

    def index
        @users = User.all
    end 

    def new
        @user = User.new
    end

    def show
    end 

    def edit
    end 

    def create
        @user = User.new(user_params)
          if @user.save
            session[:user_id] = @user.id
            redirect_to @user, notice: "User was successfully created." 
          else
            render :new
          end
      end

      def update
          if @user.update(user_params)
            redirect_to @user, notice: "User was successfully updated." 
          else
            render :edit
          end
      end

      def destroy
        @user.destroy
        redirect_to root_path, notice: "User was successfully destroyed." 
      end

      private
      def set_user
        @user = User.find(params[:id])
      end
  
      def user_params
        params.require(:user).permit(:first_name, :last_name, :user_name, :profile_image, :bio, :email, :mobile, :password, :password_confirmation)
      end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: "navbar/navbar" %>
    <div class="form-container">
       <%= yield %>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>


  </body>
</html>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">



    <a class="navbar-brand" href="#">Blog</a>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Posts", root_path, class: "nav-link" %>
          <%= link_to "Log In", new_session_path, class: "nav-link" %>
          <%= link_to "Log Out", logout_path, class: "nav-link" %>
          <% if logged_in? %>
            <a class="nav-link" href="#">Signed In As <%= current_user.first_name%> </a>
          <% else %>
              <a class="nav-link" href="#">Not Signed In</a>
          <% end %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<div class="form-container">
  <%= form_with(model: post) do |form| %>
        <% if post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
              <% post.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <div class="form-container">
        <div class="form-title-container">
          <div class="field mb-3">
              <%= form.text_field :title, placeholder:"title goes here...", class:"form-control form-title" %>
          </div>

          <div class="field mb-3 premium-radio-container">
              <label class="form-label premium-form-label"><%= form.label :premium %></label>
              <div class="radio">
                <%= radio_button_tag(:premium, true) %>
                  <%= label_tag(:premium, "yes") %>
                <%= radio_button_tag(:premium, false) %>
                  <%= label_tag(:premium, "no") %>
              </div>
          </div>

          <div class="actions">
              <%= form.button %>
              <button><%= link_to 'cancel', posts_path %></button>
          </div>

        </div>

        <div class="field mb-3">
            <%= form.text_field :image_link, placeholder:"image link", class:"form-control" %>
        </div>

        <div class="field mb-3">
            <%= form.text_area :content, placeholder:"content", class:"form-control" %>
        </div>

 

      

        <% end %>
      </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="head-container">
    <h1>Posts</h1>

    <% if current_user&.admin %> 
      <%= link_to 'Create Post', new_post_path, class:"btn btn-primary" %>
    <% end %>

  </div>

  <div class="card-container">
    <% @posts.each do |post| %>
        <div class="card" style="width: 18rem;">
          <img src="<%= post.image_link %>" class="card-img-top" style="height: 18rem;"alt="missing image">
          <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post %></h5>
            <p class="card-text"><%= post.content.truncate(100) %></p>
            <p class="card-text">Prem: <%= post.premium %></p>
            <div class="card-button">
              <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
        </div>
    <% end %>
  </div>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-container">
  <div class="show-header">
    <div class="show-left">
      <h2><strong><%= @post.title %></strong></h2>
    </div>
    <div class="show-right">
    <% if current_user.admin %>
      <p class="show-right-el"><strong>Premium: </strong><%= @post.premium %></p>
      <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-warning" %>
     <%= link_to 'Destroy', @post, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </div>
  </div>
  <% if @post.image_link %>
    <%= image_tag(@post.image_link, width:"980") %>
  <% end %>

  <% if current_user.admin %>
    <p contenteditable="true"><strong>Content: </strong><%= @post.content %></p>
  <% else %>
      <p><strong>Content: </strong><%= @post.content %></p>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="form-container">
  <%= form_with(model: user) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    
    
      <div class="field mb-3">
        <label class="form-label"><%= form.label :first_name %></label>
        <div class="form-control"><%= form.text_field :first_name %></div>
      </div>
      
      <div class="field mb-3">
        <label class="form-label"><%= form.label :last_name %></label>
        <div class="form-control"><%= form.text_field :last_name %></div>
      </div>

      <div class="field mb-3">
        <label class="form-label"><%= form.label :user_name %></label>
        <div class="form-control"><%= form.text_field :user_name %></div>
      </div>

      <div class="field mb-3">
        <label class="form-label"><%= form.label :profile_image %></label>
        <div class="form-control"><%= form.text_field :profile_image %></div>
      </div>

      <div class="field mb-3">
        <label class="form-label"><%= form.label :email %></label>
        <div class="form-control"><%= form.text_field :email %></div>
      </div>

      <div class="field mb-3">
        <label class="form-label"><%= form.label :bio %></label>
        <div class="form-control"><%= form.text_field :bio %></div>
      </div>

      <div class="field mb-3">
        <label class="form-label"><%= form.label :mobile %></label>
        <div class="form-control"><%= form.text_field :mobile %></div>
      </div>

      <div class="field  mb-3">
        <label class="form-label"><%= form.label :password %></label>
        <div class="form-control"><%= form.password_field :password %></div>
      </div>

      <div class="field">
        <label class="form-label"><%= form.label :password_confirmation %></label>
        <div class="form-control"><%= form.password_field :password_confirmation %></div>
      </div><br>

      <div class="actions">
        <%= form.submit %>
      </div>

    <% end %>
    
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="head-container">
  <h1>Users</h1>
  <%= link_to 'New User', new_user_path %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.first_name, user  %> <%= link_to user.last_name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.bio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Create Your User Account</h1>



<%= render 'form', user: @user %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show-container">
  <div class="home-container">
    <h3><%= current_user.first_name %>'s Profile</h3>

    <% if @user.profile_image %>
     
        <%= image_tag(@user.profile_image, width:"200") %>
     
    <% end %>

    <p>
      <%= @user.bio %>
    </p>

    <p><%= @user.email %></p>
    
      <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-warning" %> 
      <%= link_to 'Destroy', user_path(@user), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Back', users_path, class:"btn btn-info"  %>
  </div>
</div>